// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package core

import (
	"time"
)

const TableNameProperty = "properties"

// Property mapped from table <properties>
type Property struct {
	Key       string    `gorm:"column:key;type:character varying(255);primaryKey" json:"key"`
	Value     string    `gorm:"column:value;type:character varying(255)" json:"value"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:timestamp with time zone" json:"updated_at"`
}

// TableName Property's table name
func (*Property) TableName() string {
	return TableNameProperty
}
