// Code generated by "stringer -type=TurnErrorCode -linecomment"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TurnErrorCodeInternalServer-1]
	_ = x[TurnErrorCodeConvNotFound-2]
	_ = x[TurnErrorCodeBotNotFound-3]
	_ = x[TurnErrorCodeChatModelNotFound-4]
	_ = x[TurnErrorCodeChatModelCallError-5]
}

const _TurnErrorCode_name = "Internal Server ErrorConversation Not FoundBot Not FoundChat Model Not FoundTurnErrorCodeChatModelCallError"

var _TurnErrorCode_index = [...]uint8{0, 21, 43, 56, 76, 107}

func (i TurnErrorCode) String() string {
	i -= 1
	if i < 0 || i >= TurnErrorCode(len(_TurnErrorCode_index)-1) {
		return "TurnErrorCode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TurnErrorCode_name[_TurnErrorCode_index[i]:_TurnErrorCode_index[i+1]]
}
