// Code generated by "stringer -type=TurnStatus -linecomment --trimprefix TurnStatus"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TurnStatusInit-0]
	_ = x[TurnStatusProcessing-1]
	_ = x[TurnStatusSuccess-2]
	_ = x[TurnStatusFailed-3]
}

const _TurnStatus_name = "InitProcessingSuccessFailed"

var _TurnStatus_index = [...]uint8{0, 4, 14, 21, 27}

func (i TurnStatus) String() string {
	if i < 0 || i >= TurnStatus(len(_TurnStatus_index)-1) {
		return "TurnStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TurnStatus_name[_TurnStatus_index[i]:_TurnStatus_index[i+1]]
}
